# Generated by Django 3.0.3 on 2020-06-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_auto_20200606_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('products', models.ManyToManyField(blank=True, null=True, to='menu.Alimento')),
            ],
        ),
    ]
