# Generated by Django 3.0.3 on 2020-06-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200606_2127'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarritoCliente',
            new_name='Carrito',
        ),
    ]
