# Generated by Django 3.0.3 on 2020-06-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_ordenar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenar',
            old_name='item',
            new_name='alimento',
        ),
    ]
