# Generated by Django 3.0.3 on 2020-06-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_auto_20200607_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='precio',
            new_name='total',
        ),
    ]
