# Generated by Django 3.0.3 on 2020-06-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_auto_20200607_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='ordenado',
            field=models.BooleanField(default=0),
        ),
    ]
