# Generated by Django 3.0.3 on 2020-06-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_carrito_ordenado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenar',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
