# Generated by Django 3.0.3 on 2020-06-08 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrito', '0008_ordenar_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenar',
            name='ordenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
