# Generated by Django 3.0.3 on 2020-06-13 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrito', '0009_auto_20200608_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.RemoveField(
            model_name='ordenar',
            name='ordenado',
        ),
        migrations.RemoveField(
            model_name='ordenar',
            name='user',
        ),
        migrations.AddField(
            model_name='carrito',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='alimentos',
            field=models.ManyToManyField(to='carrito.Ordenar'),
        ),
    ]
