# Generated by Django 3.0.3 on 2020-06-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20200608_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='tipo_usuario',
            field=models.CharField(default='Administrador', max_length=13),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='tipo_usuario',
            field=models.CharField(default='Repartidor', max_length=10),
        ),
    ]
