# Generated by Django 3.0.3 on 2020-06-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200608_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'permissions': [('es_administrador', 'Administrador')]},
        ),
    ]
