# Generated by Django 3.0.3 on 2020-06-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200608_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'permissions': [('es_administrador', 'Acceso_Administrador')]},
        ),
        migrations.AlterModelOptions(
            name='repartidor',
            options={'permissions': [('es_repartidor', 'Acceso_Repartidor')]},
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='tipo_usuario',
        ),
    ]
