# Generated by Django 3.0.3 on 2020-06-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200606_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='rden',
            new_name='orden',
        ),
    ]
