# Generated by Django 3.0.3 on 2020-06-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200606_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
