# Generated by Django 3.0.3 on 2020-06-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200606_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
