# Generated by Django 3.0.3 on 2020-06-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alimento_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='cantidad',
        ),
    ]
