# Generated by Django 3.0.3 on 2020-06-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200613_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
