# Generated by Django 3.0.3 on 2020-06-05 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200523_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercliente',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(55)\\d{8}', 'El número debe estár en formato LADA.')]),
        ),
    ]
