# Generated by Django 3.0.3 on 2020-06-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200605_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercliente',
            name='tipo_usuario',
            field=models.CharField(default='Cliente', max_length=7),
        ),
    ]
