# Generated by Django 3.0.3 on 2020-06-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_usercliente_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercliente',
            options={'permissions': [('es_cliente', 'Acceso_Cliente')]},
        ),
        migrations.RemoveField(
            model_name='usercliente',
            name='tipo_usuario',
        ),
    ]
