# Generated by Django 3.0.3 on 2020-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_alimento_cantidad'),
        ('cliente', '0008_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='alimentos',
            field=models.ManyToManyField(blank=True, to='menu.Alimento'),
        ),
    ]
